version: '3.5'

services:
  brisbane-web:
    container_name: brisbane-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - '1500:80'
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - brisbane-app
    networks:
      - brisbane-network

  brisbane-app:
    container_name: brisbane-app
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    ###> XDEBUG 3 ###
    # Use your client IP here
    # Linux: run "ip a | grep docker0"
    # Windows (with WSL2) and Mac: host.docker.internal
    environment:
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=brisbane
    networks:
      - brisbane-network
    depends_on:
      - brisbane-mysql

  brisbane-mysql:
    container_name: brisbane-mysql
    image: mariadb:10.5.8
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: mysql_symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - brisbane-mysql-data:/var/lib/mysql
    networks:
      - brisbane-network
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

networks:
  brisbane-network:

volumes:
  brisbane-mysql-data:
